### PR TITLE
Made the navigation bar responsive

### PR DESCRIPTION
**Pull request by sboamah**
I made the text sizes responsive. @kushal1223 Do you think that the navigation bar can be made to only show for caregivers?

### CODE REVIEW

**Review by LDomadia — CHANGES_REQUESTED** [review]
Simulator Screen Shot - iPhone 13 - 2021-12-02 at 18 49 06

The middle button text doesn't fit entirely on the screen, is this okay or needs to be changed?

**Comment by sboamah** [comment]
> 
@LDomadia I made the font size smaller. Is it better? iOS is always giving me problems.

**Comment by LDomadia** [comment]
@sboamah It still looks the same. It isn't really a big deal to fix it now, we can look back into it in the future. I'll approve the PR for now. Also I changed the icon for the Progress Report, hopefully it's better now.

**Review by LDomadia — APPROVED** [review]

**Comment by LDomadia** [comment]
closes #27

**Review by Jhector10 — APPROVED** [review]

**Pull request merged**
